services:
  - type: web
    name: server
    env: docker
    rootDir: ./server
    repo: https://github.com/your-repo/t-lecture # Replace with your repository URL
    region: oregon
    plan: free
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: t-lecture-db
          property: connectionString
  - type: web
    name: client
    env: static
    rootDir: ./client
    repo: https://github.com/your-repo/t-lecture # Replace with your repository URL
    region: oregon
    plan: free
    buildFilter:
      paths:
      - client/**
    buildCommand: npm install && npm run build
    staticPublishPath: ./out

databases:
  - name: t-lecture-db
    databaseName: t-lecture
    plan: free
